In [ ]:
class Employee:
    num_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_employees += 1

    @staticmethod
    def average_salary(employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, experience):
        super().__init__(name, family, salary, department)
        self.experience = experience

employee1 = Employee("Tina", "Family A", 80000, "Manager")
employee2 = Employee("Sony", "Family B", 90000, "HR")

fulltime_employee1 = FulltimeEmployee("Teju", "Family C", 60000, "IT", 5)
fulltime_employee2 = FulltimeEmployee("denial klein", "Family D", 70000, "Engineering", 7)

employees = [employee1, employee2, fulltime_employee1, fulltime_employee2]
avg_salary = Employee.average_salary(employees)

print("Total number of employees:", Employee.num_employees)
print("Average salary:", avg_salary)


Total number of employees: 4
Average salary: 75000.0


In [ ]:
import numpy as np
random_vector = np.random.uniform(1, 20, size=20)
print("Original array:")
print(random_vector)

reshaped_array = random_vector.reshape(4, 5)

max_indices = np.argmax(reshaped_array, axis=1)

reshaped_array[np.arange(4), max_indices] = 0

print("\nReshaped array:")
print(reshaped_array)


Original array:
[15.18899937  4.36887899  4.46428028 18.20534568  9.64358665 14.92202489
  4.53452766  8.77560599  8.35979169 16.11471042  5.50018786  8.64680085
  7.57532706 17.22517539 10.29482561  3.22786403 17.48553228 10.65494929
  4.642088    7.76646111]

Reshaped array:
[[15.18899937  4.36887899  4.46428028  0.          9.64358665]
 [14.92202489  4.53452766  8.77560599  8.35979169  0.        ]
 [ 5.50018786  8.64680085  7.57532706  0.         10.29482561]
 [ 3.22786403  0.         10.65494929  4.642088    7.76646111]]
